### ISSUE TITLE
click save, then click save and close will get following error response

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#12]
<img width="238" alt="screen shot 2017-03-31 at 8 48 07 am" src="https://cloud.githubusercontent.com/assets/11949273/24558327/9942933e-15ef-11e7-8e52-1a06f6a466c4.png">

**Comment by pauldaustin** [comment]
Need more information

1. Which page were you on
2. What data was on the page before the error (e.g. a scree shot).
3. Look in the gwa-admin.log for that timestamp and include the stacktrace.

**Comment by ll911** [comment]
API tab, updating host, 
```
ca.bc.gov.gwa.http.HttpStatusException: Conflict
POST ${KONG_ADMIN} HTTP/1.1
	at ca.bc.gov.gwa.http.JsonHttpClient.executeRequest(JsonHttpClient.java:93)
	at ca.bc.gov.gwa.http.JsonHttpClient.executeRequestJson(JsonHttpClient.java:104)
	at ca.bc.gov.gwa.http.JsonHttpClient.post(JsonHttpClient.java:142)
	at ca.bc.gov.gwa.servlet.ApiService.apiUpdatePlugin(ApiService.java:327)
	at ca.bc.gov.gwa.servlet.ApiService.lambda$apiUpdate$3(ApiService.java:291)
	at ca.bc.gov.gwa.servlet.ApiService.handleRequest(ApiService.java:921)
	at ca.bc.gov.gwa.servlet.ApiService.apiUpdate(ApiService.java:278)
	at ca.bc.gov.gwa.servlet.ApiServlet.doPut(ApiServlet.java:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at ca.bc.gov.gwa.servlet.BaseServlet.service(BaseServlet.java:89)
	at ca.bc.gov.gwa.servlet.BaseAdminServlet.service(BaseAdminServlet.java:16)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at ca.bc.gov.gwa.servlet.siteminder.SiteminderAuthenticationFilter.doFilter(SiteminderAuthenticationFilter.java:74)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pauldaustin** [comment]
Which API?

**Comment by ll911** [comment]
```fe1e367f-aac5-415f-8f65-081e63c94c04```
it doesn't matter which API, the error happened when you click on "save and close" after you click "save" already.

**Comment by pauldaustin** [comment]
Leo,

I still need the complete list of steps.

1. Click on Add API
2. Enter (list values for all fields that were entered).
3. Click Save button
4. Change (list of fields and values changed)
5. Click Save and close button
6. Error occurs

More information makes resolving the errors easier

**Comment by pauldaustin** [comment]
Also use the api name rather than id as I can find that quicker

**Comment by ll911** [comment]
you can try with any API.
1. Click on Add API
2. Enter (list values for all fields that were entered).
3. Click Save button
4. Click Save and close button
5. Error occurs

**Comment by pauldaustin** [comment]
If there was an error adding a plugin when creating an API it didn't redirect to the "edit" page. This then caused more issues. Resolved now.

**Comment by ll911** [comment]
confirmed
