### ISSUE TITLE
some plugin not working

### ISSUE THREAD

**Issue by ll911** [bcgov/gwa#16]
```
2017-03-31 13:35:30,019	ERROR	ca.bc.gov.gwa.servlet.ApiService	ca.bc.gov.gwa.http.HttpStatusException: Bad Request
POST http://$KONG_ADMIN/apis/$API_ID/plugins HTTP/1.1
{"config.append":"append is not a table","config.add":"add is not a table","config.replace":"replace is not a table","config.remove":"remove is not a table"}

ca.bc.gov.gwa.http.HttpStatusException: Bad Request
POST http://$KONG_ADMIN/apis/$API_ID/plugins HTTP/1.1
	at ca.bc.gov.gwa.http.JsonHttpClient.executeRequest(JsonHttpClient.java:93)
	at ca.bc.gov.gwa.http.JsonHttpClient.executeRequestJson(JsonHttpClient.java:104)
	at ca.bc.gov.gwa.http.JsonHttpClient.post(JsonHttpClient.java:142)
	at ca.bc.gov.gwa.servlet.ApiService.lambda$handleAdd$10(ApiService.java:943)
	at ca.bc.gov.gwa.servlet.ApiService.handleRequest(ApiService.java:992)
	at ca.bc.gov.gwa.servlet.ApiService.handleAdd(ApiService.java:942)
	at ca.bc.gov.gwa.servlet.ApiServlet.doPost(ApiServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at ca.bc.gov.gwa.servlet.BaseServlet.service(BaseServlet.java:89)
	at ca.bc.gov.gwa.servlet.BaseAdminServlet.service(BaseAdminServlet.java:16)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at ca.bc.gov.gwa.servlet.siteminder.SiteminderAuthenticationFilter.doFilter(SiteminderAuthenticationFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
2017-03-31 13:35:32,397	ERROR	ca.bc.gov.gwa.servlet.ApiService	ca.bc.gov.gwa.http.HttpStatusException: Bad Request
POST http://$KONG_ADMIN/apis/$API_ID/plugins HTTP/1.1
{"config.append":"append is not a table","config.add":"add is not a table","config.replace":"replace is not a table","config.remove":"remove is not a table"}

ca.bc.gov.gwa.http.HttpStatusException: Bad Request
POST http://$KONG_ADMIN/apis/$API_ID/plugins HTTP/1.1
	at ca.bc.gov.gwa.http.JsonHttpClient.executeRequest(JsonHttpClient.java:93)
	at ca.bc.gov.gwa.http.JsonHttpClient.executeRequestJson(JsonHttpClient.java:104)
	at ca.bc.gov.gwa.http.JsonHttpClient.post(JsonHttpClient.java:142)
	at ca.bc.gov.gwa.servlet.ApiService.lambda$handleAdd$10(ApiService.java:943)
	at ca.bc.gov.gwa.servlet.ApiService.handleRequest(ApiService.java:992)
	at ca.bc.gov.gwa.servlet.ApiService.handleAdd(ApiService.java:942)
	at ca.bc.gov.gwa.servlet.ApiServlet.doPost(ApiServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at ca.bc.gov.gwa.servlet.BaseServlet.service(BaseServlet.java:89)
	at ca.bc.gov.gwa.servlet.BaseAdminServlet.service(BaseAdminServlet.java:16)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
	at ca.bc.gov.gwa.servlet.siteminder.SiteminderAuthenticationFilter.doFilter(SiteminderAuthenticationFilter.java:75)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
```
see attached screenshot
<img width="1145" alt="screen shot 2017-03-31 at 1 37 42 pm" src="https://cloud.githubusercontent.com/assets/11949273/24568632/8fd46fd4-1617-11e7-86b4-29e00c59b6e8.png">

**Comment by pauldaustin** [comment]
The scope of work only included UI for the acl and rate limit plugins.

The full plugin configuration is a bonus feature.

At this time it does not support plugins that require a table for field values. That will be an enhancement in the future.

**Comment by ll911** [comment]
@BK01 please add to next phase of GWA
